[mailbox/email] new designs + mobile view
nylas/components pull request #15
Opened 2021-07-27 20:23 UTC by isabellaenriquez

- implemented new UI for Email and Mailbox, including mobile view

# Readiness checklist

- [] Cypress tests passing?
- [] New cypress tests added?
- [] Included before/after screenshots, if the change is visual

# License

I confirm that this contribution is made under the terms of the MIT license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2021-07-27 20:29 UTC, wonka-lighthouse reviewed
![](https://img.shields.io/badge/Accessibility-61-orange?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-100-green?style=flat-square) ![](https://img.shields.io/badge/Performance-96-green?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-30-red?style=flat-square) ![](https://img.shields.io/badge/SEO-82-orange?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://localhost:8000/components/agenda/src/index.html |

![](https://img.shields.io/badge/Accessibility-62-orange?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-100-green?style=flat-square) ![](https://img.shields.io/badge/Performance-98-green?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-30-red?style=flat-square) ![](https://img.shields.io/badge/SEO-91-green?style=flat-square) 
| Device | URL |
|--|--|
| mobile | http://localhost:8000/components/composer/src/index.html |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["mobile:http://localhost:8000/components/agenda/src/index.html","mobile:http://localhost:8000/components/composer/src/index.html"]COMMENT_ID -->

2021-07-29 20:29 UTC, isabellaenriquez commented
@srishaank I couldn't tag you as a reviewer so just going to tag you here!

2021-07-29 20:59 UTC, philrenaud requested changes
A few spacing revisions requested:

- feels weird to have everything centered while still collapsed here
![CleanShot 2021-07-29 at 16 56 06](https://user-images.githubusercontent.com/713991/127564663-f2b6c410-ebf9-49fa-bccd-e249f6501cc9.png)

- "expanding your message" is present on un-opened messages when it oughtn't be:
![CleanShot 2021-07-29 at 16 57 40](https://user-images.githubusercontent.com/713991/127564784-73daaba1-cc41-4eec-92e3-da2f13248b04.png)

- whitespace between email items is taller than it should be:
![CleanShot 2021-07-29 at 16 58 27](https://user-images.githubusercontent.com/713991/127564888-48fd1171-983c-4ef1-81c4-bac2a9d579c2.png)

2021-07-29 21:37 UTC, isabellaenriquez commented
@philrenaud thanks for pointing those out! for the first one, I attached a version where the lines go all the way as in the Figma to this message, but @srishaank what are you thoughts on the alignment?
<img width="1440" alt="Screen Shot 2021-07-29 at 5 35 28 PM" src="https://user-images.githubusercontent.com/45607721/127568948-f44dfe6d-67be-41f3-8d87-36ca9d9fb7db.png">

2021-07-30 16:01 UTC, srishaank commented
Poked through some other products and I think this is our best bet. Maintain a 24pt margin once you get to wider desktop breakpoints.


<img width="1343" alt="Screenshot 2021-07-30 at 11 50 27 AM" src="https://user-images.githubusercontent.com/11324146/127678831-3e040970-5b10-477f-a45d-f8f3bb8ea575.png">

2021-07-30 21:32 UTC, philrenaud approved these changes

2021-07-30 21:38 UTC, pooja169usp commented on components/mailbox/src/Mailbox.svelte
> +    console.log(openedEmailData);
remove log 🔪

2021-07-30 21:40 UTC, pooja169usp approved these changes

2021-07-30 23:14 UTC, merged