Add ability for Composer to save email to draft
nylas/components pull request #383
Opened 2022-02-08 16:20 UTC by yifanplanet

# Code changes

- [ ]

# Readiness checklist

- [ ] Added changes to component `CHANGELOG.md`
- [ ] New property added? make sure to update `component/src/properties.json`
- [ ] Cypress tests passing?
- [ ] New cypress tests added?
- [ ] Included before/after screenshots, if the change is visual

# License

I confirm that this contribution is made under the terms of the MIT license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2022-02-09 05:57 UTC, yifanplanet commented
Currently individual draft message is not showing in expanded thread in Email component, in order to better integrate this, created the feature story:
https://app.shortcut.com/nylas/story/81020/display-and-edit-draft-as-individual-message-in-a-email-component-thread

2022-02-09 14:22 UTC, philrenaud requested changes
Code and tests look good. A couple change requests:
- the Save as Drafts button should be added to the tabindex / be tabbable. Right now after tabbing out of the body, you go right to the Send button, which is good and we shouldn't change. But after that, we should tab to the Save as Drafts button
- the existence of this button should be predicated on a `show_save_as_draft` prop, or something similarly named. Don't assume end users will always want this. It's fine for it to default to true.

2022-02-09 16:50 UTC, pooja169usp requested changes
@yifanplanet A couple things I noticed:
1. When a message has an attachedFile and is saved as a draft, we should make an additional request to `/files` endpoint, get the file object and add it to the draft message being stored. 
2. Every time I save a message as draft within a thread, we are creating a new draft message. It should ideally update the existing draft, or we should have a way of showing the draft message (like gmail).

2022-02-09 20:16 UTC, yifanplanet commented on components/composer/src/init.spec.js
> +          },
Thanks for the review! To respond your change request, I've made a few changes in my new commit:
- I changed the button to be better semantically described by using interactive elements and to be tabbable.
- Added prop `show_save_as_draft` to show save draft button when only true, default to true.
- Added callback `afterSaveSuccess` and `afterSaveError`.
- The test cases used callback function for saving draft which doesn't test the actual API endpoints.

2022-02-09 20:21 UTC, yifanplanet commented
> @yifanplanet A couple things I noticed:
> 
> 1. When a message has an attachedFile and is saved as a draft, we should make an additional request to `/files` endpoint, get the file object and add it to the draft message being stored.
> 2. Every time I save a message as draft within a thread, we are creating a new draft message. It should ideally update the existing draft, or we should have a way of showing the draft message (like gmail).

@pooja169usp Thanks for the review! For your questions:
- I updated the code in my latest commit which update draft when message `id` and `version` is provided. For displaying and editing existing draft messages in mailbox, I've added the shortcut story specifically for that. [shortcut 81020](https://app.shortcut.com/nylas/story/81020/display-and-edit-draft-as-individual-message-in-a-email-component-thread)
- There's no need to add request to `/files` endpoints since it's already called when the file is attached and the file id is updated along with draft message and will be saved together as draft.

2022-02-10 15:03 UTC, philrenaud approved these changes

2022-02-10 22:43 UTC, pooja169usp approved these changes

2022-02-11 00:10 UTC, merged